### ISSUE TITLE
raise child_exception OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rubenohayon** [yaoli/arctic-capgen-vid#11]
Hi everybody, 

When I tried to run metrics.py I have this error i don't know where does it come could you help me please 

```
python metrics.py
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
loading youtube2text googlenet features
uneven minibath chunking, overall 20, last one 11
uneven minibath chunking, overall 20, last one 8
init COCO-EVAL scorer
tokenization...
Traceback (most recent call last):
  File "metrics.py", line 202, in <module>
    test_cocoeval()
  File "metrics.py", line 198, in test_cocoeval
    valid_score, test_score = score_with_cocoeval(samples_valid, samples_test, engine)
  File "metrics.py", line 91, in score_with_cocoeval
    valid_score = scorer.score(gts_valid, samples_valid, engine.valid_ids)
  File "/home/ruben/arctic-capgen-vid-master/cocoeval.py", line 22, in score
    gts  = tokenizer.tokenize(gts)
  File "/home/ruben/coco-caption-master/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by rubenohayon** [comment]
I fixed the problem : add shell=True in subprocess.popen
