### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by YangXS** [yaoli/arctic-capgen-vid#5]
Thank @yaoli for the great work. 
I successfully compiled and run the packages.
However, the running stopped in about half day.
The errors  are as follows.
Does anyone has the same error ?
'''
init COCO-EVAL scorer
tokenization...
Traceback (most recent call last):
  File "train_model.py", line 103, in <module>
    sys.exit(main(state))
  File "train_model.py", line 89, in main
    train_from_scratch(config, state, channel)
  File "train_model.py", line 82, in train_from_scratch
    model_attention.train_from_scratch(state, channel)
  File "/mnt/pan_sdd1/VideoToLanguage/Solutions/arctic-capgen-vid-master/model_attention.py", line 1306, in train_from_scratch
    model.train(**state.attention)
  File "/mnt/pan_sdd1/VideoToLanguage/Solutions/arctic-capgen-vid-master/model_attention.py", line 1177, in train
    f_init=f_init, f_next=f_next, model=self
  File "/mnt/pan_sdd1/VideoToLanguage/Solutions/arctic-capgen-vid-master/metrics.py", line 174, in compute_score
    valid_score, test_score = score_with_cocoeval(samples_valid, samples_test, engine)
  File "/mnt/pan_sdd1/VideoToLanguage/Solutions/arctic-capgen-vid-master/metrics.py", line 91, in score_with_cocoeval
    valid_score = scorer.score(gts_valid, samples_valid, engine.valid_ids)
  File "/mnt/pan_sdd1/VideoToLanguage/Solutions/arctic-capgen-vid-master/cocoeval.py", line 22, in score
    gts  = tokenizer.tokenize(gts)
  File "/home/mmc/Downloads/coco-caption-master/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1143, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
'''

**Comment by yaoli** [comment]
Have you tried the trick I mentioned in the README file? I think that could be the fix.

**Comment by YangXS** [comment]
Thanks very much for your suggestion, I will try it :)

**Comment by sxs4337** [comment]
Adding "CUDA_LAUNCH_BLOCKING=1" to the Theano command also prevented this error. It makes it a little slower but solved the error.

**Comment by YangXS** [comment]
@sxs4337 , thanks for your advice. I have tried the trick mentioned at the end of the README. It works well.
